autoprice: false
inventoryrows: 4
items:
  - 'DIAMOND'
  - 'EMERALD'
  - 'GOLD_INGOT'
  - 'IRON_INGOT'
  - 'LAPIS_LAZULI'
  - 'OAK_LOG'
  - 'DARK_OAK_LOG'
  - 'SAND'
  - 'POTATO'
buyprices:
  DIAMOND: 15
  EMERALD: 10
  GOLD_INGOT: 8
  IRON_INGOT: 4
  LAPIS_LAZULI: 1.75
  OAK_LOG: 0.95
  DARK_OAK_LOG: 0.95
  SAND: 0.1
  POTATO: 0.25
sellprices:
  DIAMOND: 12
  EMERALD: 7.50
  GOLD_INGOT: 5.50
  IRON_INGOT: 2.25
  LAPIS_LAZULI: 1.25
  OAK_LOG: 0.35
  DARK_OAK_LOG: 0.40
  SAND: 0.05
  POTATO: 0.04
categories:
  GENERAL:
    - 'LAPIS_LAZULI'
  METAL:
    - 'DIAMOND'
    - 'EMERALD'
    - 'GOLD_INGOT'
    - 'IRON_INGOT'
  WOOD:
    - 'OAK_LOG'
    - 'DARK_OAK_LOG'
  ROCK:
    - 'SAND'
  FOOD:
    - 'POTATO'



